/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'author' : string,
  'isFeatured' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface NewsletterSignup { 'createdAt' : bigint, 'email' : string }
export interface PageContent {
  'title' : string,
  'content' : string,
  'lastModified' : bigint,
}
export interface Product {
  'id' : bigint,
  'mrp' : bigint,
  'status' : ProductStatus,
  'title' : string,
  'imageBlob' : [] | [ExternalBlob],
  'createdAt' : bigint,
  'description' : [] | [string],
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : ProductCategory,
  'affiliateLink' : string,
  'price' : bigint,
  'discountPercentage' : bigint,
}
export type ProductCategory = { 'jewellery' : null } |
  { 'sarees' : null } |
  { 'bottomWear' : null } |
  { 'dressMaterial' : null } |
  { 'festive' : null } |
  { 'kurtasKurtis' : null } |
  { 'gowns' : null } |
  { 'salwarSuits' : null } |
  { 'sportswear' : null } |
  { 'lehengaCholis' : null } |
  { 'chunnisDupattas' : null } |
  { 'westernWear' : null };
export interface ProductInput {
  'mrp' : bigint,
  'title' : string,
  'description' : [] | [string],
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : ProductCategory,
  'affiliateLink' : string,
  'price' : bigint,
  'discountPercentage' : bigint,
}
export type ProductStatus = { 'active' : null } |
  { 'inactive' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBlogPost' : ActorMethod<
    [string, string, string, string, boolean],
    BlogPost
  >,
  'addProduct' : ActorMethod<[string, ProductInput], Product>,
  'addProductWithImage' : ActorMethod<
    [string, ProductInput, ExternalBlob],
    Product
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpdatePages' : ActorMethod<
    [string, Array<[string, string, string]>],
    undefined
  >,
  'checkAuth' : ActorMethod<[string], boolean>,
  'deleteBlogPost' : ActorMethod<[string, bigint], undefined>,
  'deleteProduct' : ActorMethod<[string, bigint], undefined>,
  'filterProducts' : ActorMethod<
    [
      [] | [ProductCategory],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
    ],
    Array<Product>
  >,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAllPages' : ActorMethod<[string], Array<[string, PageContent]>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBlogPostById' : ActorMethod<[bigint], BlogPost>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFashionProducts' : ActorMethod<[], Array<Product>>,
  'getFeaturedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getGoogleVerificationFilename' : ActorMethod<[], [] | [string]>,
  'getNewsletterSignups' : ActorMethod<[string], Array<NewsletterSignup>>,
  'getPage' : ActorMethod<[string], PageContent>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProductCounter' : ActorMethod<[string], bigint>,
  'getProductForEdit' : ActorMethod<[string, bigint], [] | [Product]>,
  'getProductImage' : ActorMethod<[bigint], [] | [ExternalBlob]>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getProductsByDiscountRange' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getProductsByPriceRange' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getRobotsTxt' : ActorMethod<[], string>,
  'getSiteInfo' : ActorMethod<
    [],
    {
      'categories' : Array<string>,
      'tagline' : string,
      'siteName' : string,
      'affiliateDisclaimer' : string,
    }
  >,
  'getSitemap' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], string>,
  'logout' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'setGoogleVerificationFilename' : ActorMethod<[string, string], undefined>,
  'subscribeNewsletter' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBlogPost' : ActorMethod<
    [string, bigint, string, string, string, boolean],
    BlogPost
  >,
  'updatePage' : ActorMethod<[string, string, string, string], undefined>,
  'updateProduct' : ActorMethod<[string, bigint, ProductInput], Product>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];