/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type FashionCategory = { 'kurtaKurtis' : null } |
  { 'sarees' : null } |
  { 'festive' : null } |
  { 'gowns' : null } |
  { 'salwarSuits' : null } |
  { 'sportsWear' : null } |
  { 'lehengaCholis' : null } |
  { 'westernWear' : null };
export type JewelleryCategory = { 'necklaces' : null } |
  { 'rings' : null };
export interface Product {
  'id' : bigint,
  'mrp' : bigint,
  'status' : ProductStatus,
  'title' : string,
  'imageBlob' : [] | [ExternalBlob],
  'createdAt' : bigint,
  'description' : [] | [string],
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : ProductCategory,
  'affiliateLink' : string,
  'price' : bigint,
  'discountPercentage' : bigint,
}
export type ProductCategory = { 'jewellery' : JewelleryCategory } |
  { 'fashion' : FashionCategory };
export interface ProductInput {
  'mrp' : bigint,
  'title' : string,
  'description' : [] | [string],
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : ProductCategory,
  'affiliateLink' : string,
  'price' : bigint,
  'discountPercentage' : bigint,
}
export type ProductStatus = { 'active' : null } |
  { 'inactive' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[ProductInput], bigint>,
  'addUser' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateUser' : ActorMethod<[string, string], [] | [string]>,
  'cleanupExpiredSessions' : ActorMethod<[], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'filterProducts' : ActorMethod<
    [
      [] | [ProductCategory],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
    ],
    Array<Product>
  >,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFashionProducts' : ActorMethod<[FashionCategory], Array<Product>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProductCounter' : ActorMethod<[], bigint>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getProductsByDiscountRange' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getProductsByPriceRange' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logout' : ActorMethod<[string], undefined>,
  'removeUser' : ActorMethod<[string], undefined>,
  'restoreProducts' : ActorMethod<[Array<Product>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];