/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'author' : IDL.Text,
  'isFeatured' : IDL.Bool,
});
export const ProductCategory = IDL.Variant({
  'jewellery' : IDL.Null,
  'sarees' : IDL.Null,
  'bottomWear' : IDL.Null,
  'dressMaterial' : IDL.Null,
  'festive' : IDL.Null,
  'kurtasKurtis' : IDL.Null,
  'gowns' : IDL.Null,
  'salwarSuits' : IDL.Null,
  'sportswear' : IDL.Null,
  'lehengaCholis' : IDL.Null,
  'chunnisDupattas' : IDL.Null,
  'westernWear' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'mrp' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : ProductCategory,
  'affiliateLink' : IDL.Text,
  'price' : IDL.Nat,
  'discountPercentage' : IDL.Nat,
});
export const ProductStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'mrp' : IDL.Nat,
  'status' : ProductStatus,
  'title' : IDL.Text,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'createdAt' : IDL.Int,
  'description' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : ProductCategory,
  'affiliateLink' : IDL.Text,
  'price' : IDL.Nat,
  'discountPercentage' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PageContent = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'lastModified' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const NewsletterSignup = IDL.Record({
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [BlogPost],
      [],
    ),
  'addProduct' : IDL.Func([IDL.Text, ProductInput], [Product], []),
  'addProductWithImage' : IDL.Func(
      [IDL.Text, ProductInput, ExternalBlob],
      [Product],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpdatePages' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text))],
      [],
      [],
    ),
  'checkAuth' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'deleteBlogPost' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'filterProducts' : IDL.Func(
      [
        IDL.Opt(ProductCategory),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllPages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, PageContent))],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBlogPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFashionProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getFeaturedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getGoogleVerificationFilename' : IDL.Func(
      [],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getNewsletterSignups' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NewsletterSignup)],
      ['query'],
    ),
  'getPage' : IDL.Func([IDL.Text], [PageContent], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductCounter' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getProductForEdit' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(Product)],
      ['query'],
    ),
  'getProductImage' : IDL.Func([IDL.Nat], [IDL.Opt(ExternalBlob)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsByDiscountRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getRobotsTxt' : IDL.Func([], [IDL.Text], ['query']),
  'getSiteInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'categories' : IDL.Vec(IDL.Text),
          'tagline' : IDL.Text,
          'siteName' : IDL.Text,
          'affiliateDisclaimer' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getSitemap' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'setGoogleVerificationFilename' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBlogPost' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [BlogPost],
      [],
    ),
  'updatePage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func([IDL.Text, IDL.Nat, ProductInput], [Product], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'author' : IDL.Text,
    'isFeatured' : IDL.Bool,
  });
  const ProductCategory = IDL.Variant({
    'jewellery' : IDL.Null,
    'sarees' : IDL.Null,
    'bottomWear' : IDL.Null,
    'dressMaterial' : IDL.Null,
    'festive' : IDL.Null,
    'kurtasKurtis' : IDL.Null,
    'gowns' : IDL.Null,
    'salwarSuits' : IDL.Null,
    'sportswear' : IDL.Null,
    'lehengaCholis' : IDL.Null,
    'chunnisDupattas' : IDL.Null,
    'westernWear' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'mrp' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : ProductCategory,
    'affiliateLink' : IDL.Text,
    'price' : IDL.Nat,
    'discountPercentage' : IDL.Nat,
  });
  const ProductStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'mrp' : IDL.Nat,
    'status' : ProductStatus,
    'title' : IDL.Text,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'createdAt' : IDL.Int,
    'description' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : ProductCategory,
    'affiliateLink' : IDL.Text,
    'price' : IDL.Nat,
    'discountPercentage' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PageContent = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'lastModified' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const NewsletterSignup = IDL.Record({
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [BlogPost],
        [],
      ),
    'addProduct' : IDL.Func([IDL.Text, ProductInput], [Product], []),
    'addProductWithImage' : IDL.Func(
        [IDL.Text, ProductInput, ExternalBlob],
        [Product],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpdatePages' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Text))],
        [],
        [],
      ),
    'checkAuth' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'deleteBlogPost' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'filterProducts' : IDL.Func(
        [
          IDL.Opt(ProductCategory),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllPages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, PageContent))],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBlogPostById' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFashionProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getFeaturedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getGoogleVerificationFilename' : IDL.Func(
        [],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getNewsletterSignups' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NewsletterSignup)],
        ['query'],
      ),
    'getPage' : IDL.Func([IDL.Text], [PageContent], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductCounter' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getProductForEdit' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(Product)],
        ['query'],
      ),
    'getProductImage' : IDL.Func([IDL.Nat], [IDL.Opt(ExternalBlob)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByDiscountRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getRobotsTxt' : IDL.Func([], [IDL.Text], ['query']),
    'getSiteInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'categories' : IDL.Vec(IDL.Text),
            'tagline' : IDL.Text,
            'siteName' : IDL.Text,
            'affiliateDisclaimer' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getSitemap' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'setGoogleVerificationFilename' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBlogPost' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [BlogPost],
        [],
      ),
    'updatePage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, ProductInput],
        [Product],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };